apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-topic-init
  namespace: messaging
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: topic-init
          image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
          command:
            - /bin/sh
            - -c
            - |
              rpk topic create focus.events \
                --brokers redpanda.messaging.svc.cluster.local:9092 \
                --partitions 3 \
                --replicas 1 || true
